### ISSUE TITLE
TypeError: VisionTransformer.forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by KangcongLi** [Intelligent-Computing-Research-Group/BKDSNN#2]
Hi!我在尝试运行SFormer/cifar10下的train.py时遇到了以下问题：
```
VisionTransformer.forward() takes 2 positional arguments but 3 were given
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 909, in train_one_epoch_distillation
    _, feature_T = model_teacher(input, True)
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 709, in main
    train_metrics = train_one_epoch_distillation(
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 1128, in <module>
    main()
TypeError: VisionTransformer.forward() takes 2 positional arguments but 3 were given
```

尝试把_, feature_T = model_teacher(input, True)修改为feature_T = model_teacher(input)后重新运行，报错：
```
Traceback (most recent call last):
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 1128, in <module>
    main()
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 709, in main
    train_metrics = train_one_epoch_distillation(
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/train.py", line 917, in train_one_epoch_distillation
    loss_dist_feature = loss_dist_fn(feature[0], feature_T[0])
  File "/root/anaconda3/envs/llava0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llava0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/loss.py", line 55, in forward
    loss = self.get_dis_loss(preds_S, preds_T) * self.alpha_mgd
  File "/root/kcli/BKDSNN-master/Spikingformer-CML/cifar10/loss.py", line 63, in get_dis_loss
    N, D, H, W = preds_S.shape
AttributeError: 'dict' object has no attribute 'shape'
```

麻烦您看一下，十分感谢！

**Comment by GhostCells** [comment]
请问你有教师权重文件嘛，感觉CNN那部分的代码好像少了一点

**Comment by Xzk7** [comment]
已更新Transformer上CIFAR和ImageNet的教师权重，ResNet用的是torchvision自带的。

**Comment by GhostCells** [comment]
> 已更新Transformer上CIFAR和ImageNet的教师权重，ResNet用的是torchvision自带的。

请问上面这个人的问题怎么解决，我也碰到了，把True去掉后只会返回一个logits，没有feat，请问模型是否在哪里做了调整

**Comment by KaiSUN1** [comment]
这个有解决么，我也遇到了相同的问题

**Comment by Xzk7** [comment]
抱歉才回复，需要用:
链接: https://pan.baidu.com/s/192hfqFIwijvOOrYh2IJ_FA?pwd=1wsj 提取码: 1wsj 
--来自百度网盘超级会员v6的分享
分享的vision_transformer.py替换/path/to/envs/lib/python3.10/site-packages/timm/models下的vision_transformer.py，希望有所帮助。
